Update require login redirect when login route changes
jeremyevans/rodauth pull request #396
Opened 2024-03-01 07:49 UTC by janko

When login feature is enabled, it's expected that requiring login will redirect to the login page. This won't be the case if `login_route` changes. I thought it would be convenient to have it automatically match, so that the developer doesn't have to also update `require_login_redirect` in that case.

2024-03-01 15:16 UTC, jeremyevans requested changes
I'm fine with this change, but `redirect(:require_login){"#{prefix}/login"}` should be removed, and replaced with an appropriate `auth_value_method` argument.

2024-03-03 22:19 UTC, janko commented
I added the requested change.

2024-03-04 16:39 UTC, jeremyevans commented
My apologies, I didn't realize when I requested the change that the redirect call was in a different feature (base instead of login).  So your original patch did not redefine a method.  Your original patch was correct and I'll merge that.

2024-03-04 17:16 UTC, jeremyevans commented
Cherry-picked as 0869be21335c6892792922e878dd0b5b82e2fd33

2024-03-04 17:16 UTC, closed without merging